---
area/ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"
area/python:
  - changed-files:
      - any-glob-to-any-file: "src/**/*"
area/docker:
  - changed-files:
      - any-glob-to-any-file: "Dockerfile"
